// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/auth.proto

package authv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SigninRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SigninRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SigninRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SigninRequestMultiError, or
// nil if none found.
func (m *SigninRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SigninRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for State

	if len(errors) > 0 {
		return SigninRequestMultiError(errors)
	}

	return nil
}

// SigninRequestMultiError is an error wrapping multiple validation errors
// returned by SigninRequest.ValidateAll() if the designated constraints
// aren't met.
type SigninRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SigninRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SigninRequestMultiError) AllErrors() []error { return m }

// SigninRequestValidationError is the validation error returned by
// SigninRequest.Validate if the designated constraints aren't met.
type SigninRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SigninRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SigninRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SigninRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SigninRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SigninRequestValidationError) ErrorName() string { return "SigninRequestValidationError" }

// Error satisfies the builtin error interface
func (e SigninRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSigninRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SigninRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SigninRequestValidationError{}

// Validate checks the field values on SigninReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SigninReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SigninReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SigninReplyMultiError, or
// nil if none found.
func (m *SigninReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SigninReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for State

	// no validation rules for Data

	if len(errors) > 0 {
		return SigninReplyMultiError(errors)
	}

	return nil
}

// SigninReplyMultiError is an error wrapping multiple validation errors
// returned by SigninReply.ValidateAll() if the designated constraints aren't met.
type SigninReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SigninReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SigninReplyMultiError) AllErrors() []error { return m }

// SigninReplyValidationError is the validation error returned by
// SigninReply.Validate if the designated constraints aren't met.
type SigninReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SigninReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SigninReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SigninReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SigninReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SigninReplyValidationError) ErrorName() string { return "SigninReplyValidationError" }

// Error satisfies the builtin error interface
func (e SigninReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSigninReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SigninReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SigninReplyValidationError{}
